inherit_from: .rubocop_todo.yml

require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
