inherit_from: .rubocop_todo.yml

require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
